import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen, LayoutGrid, GraduationCap, ArrowUpRight, Search, ChevronLeft, ChevronRight, X, Users, CalendarDays, Plus, LogOut, SlidersHorizontal, Check, Leaf, Code2, Database, GitBranch, Palette, RefreshCw} from 'lucide-react';
import {request, decodeUser} from './api';

import './styles.css';

const labels={OPEN:'모집 중',DRAFT:'모집 예정',CLOSED:'모집 마감',PENDING:'처리 중',CONFIRMED:'신청 완료',CANCELLED:'취소 완료'};
const money=v=>new Intl.NumberFormat('ko-KR').format(v)+'원';
const date=v=>v ? new Date(v).toLocaleDateString('ko-KR') : '미정';
function Modal({title,onClose,children}) {
  const ref=useRef();
  useEffect(()=>{const previous=document.activeElement;ref.current.focus();const handler=e=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const items=ref.current.querySelectorAll('button:not(:disabled),input,select,textarea,[tabindex="0"]');const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',handler);document.body.style.overflow=old;previous?.focus();};},[]);
  return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref}><header><h2>{title}</h2><button className="icon-button" aria-label="닫기" onClick={onClose}><X size={21}/></button></header>{children}</section></div>;
}
function Artwork({kind,index=0}) {const icons={react:Code2,spring:Leaf,design:Palette,python:Code2,sql:Database,git:GitBranch};const Icon=icons[kind]||[Code2,Leaf,Palette,Database][index%4];return <div className={`art art-${kind||index%4}`} aria-hidden="true"><span className="art-caption">CLASSROOM ORIGINAL</span><div className="art-orbit"/><div className="art-tile"><Icon size={51} strokeWidth={1.35}/></div><span className="art-code">{({react:'< React />',spring:'Spring Boot',design:'Make it yours.',python:'Hello, Python.',sql:'SELECT *',git:'Better together.'})[kind]||'Learn something new.'}</span><span className="art-dot"/></div>;}
function App(){
 const [token,setToken]=useState(()=>{const t=sessionStorage.getItem('classroom-token');return t&&decodeUser(t)?t:'';});
 const user=decodeUser(token),guest=!token,creator=user?.role==='CREATOR';
 const [view,setView]=useState('classes'),[state,setState]=useState('OPEN'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[data,setData]=useState({content:[],totalPages:0,totalElements:0}),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(null),[detail,setDetail]=useState(null),[revision,setRevision]=useState(0),[pending,setPending]=useState([]),[students,setStudents]=useState(null),[studentPage,setStudentPage]=useState(0);
 const refresh=()=>setRevision(v=>v+1);
 useEffect(()=>{let active=true;setError('');setLoading(true);request(creator?"/classes/my?page="+page+"&size=6&state="+state:view==='my'?`/enrollments/my?page=${page}&size=6`:`/classes?page=${page}&size=6${state?'&state='+state:''}`,{token}).then(d=>{if(active)setData(d);}).catch(e=>{if(active){setError(e.message);setData({content:[],totalPages:0,totalElements:0});if(e.status===401&&token){sessionStorage.removeItem('classroom-token');setToken('');setView('classes');setState('OPEN');setPage(0);setModal('login');}}}).finally(()=>active&&setLoading(false));return()=>{active=false;};},[token,creator,view,state,page,revision]);
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6500);return()=>clearTimeout(id);},[notice]);
 async function act(fn){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
 function navigate(v){if(v==='my'&&!token){setError('');setModal('login');return;}setView(v);setPage(0);setQuery('');setState(v==='my'?'':'OPEN');}
 async function openDetail(c){await act(async()=>{setStudents(null);setDetail(await request(`/classes/${c.classSeq}`,{token}));setModal('detail');});}
 async function enroll(){if(!token){setError('');setModal('login');return;}await act(async()=>{await request(`/enrollments/classes/${detail.classSeq}`,{token,method:'POST'});setPending(v=>[...v,detail.classSeq]);setNotice('신청 요청이 접수되었습니다. 내 수강 목록을 새로고침하여 최종 결과를 확인해 주세요.');setModal(null);});}
 async function logout(){
   await act(async()=>{
     try { await request('/users/logout',{token,method:'POST'}); }
     catch(e){ if(e.status!==401)throw e; }
     sessionStorage.removeItem('classroom-token');
     setToken('');setPending([]);setDetail(null);setStudents(null);setModal(null);
     setData({content:[],totalPages:0,totalElements:0});
     navigate('classes');setNotice('로그아웃되었습니다.');
   });
 }
 async function authenticate(e){e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));await act(async()=>{if(modal==='signup'){await request('/users/signup',{method:'POST',body:values});setNotice('회원가입이 완료되었습니다. 로그인해 주세요.');setModal('login');return;}const d=await request('/users/login',{method:'POST',body:values});if(!decodeUser(d.accessToken))throw new Error('로그인 응답을 확인할 수 없습니다.');sessionStorage.setItem('classroom-token',d.accessToken);setToken(d.accessToken);setPending([]);setModal(null);navigate('classes');setNotice('로그인되었습니다. 원하는 배움을 찾아보세요.');});}
 async function saveClass(e){e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));body.classPrice=Number(body.classPrice);body.classMaxCap=Number(body.classMaxCap);if(body.classEndDate<=body.classStartDate){setError('종료일은 시작일 이후로 설정해 주세요.');return;}await act(async()=>{await request(`/classes${modal==='edit'?'/'+detail.classSeq:''}`,{token,method:modal==='edit'?'PUT':'POST',body});setModal(null);setView('classes');setState('DRAFT');setPage(0);setQuery('');refresh();setNotice('강의가 저장되었습니다.');});}
 async function loadStudents(p=0){await act(async()=>{const d=await request(`/enrollments/classes/${detail.classSeq}/users?page=${p}&size=10`,{token});setStudents(d);setStudentPage(p);});}
 const shown=data.content.filter(c=>c.classTitle?.toLowerCase().includes(query.toLowerCase()));
 return <div className="app"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('classes');}}><span className="brand-mark"><BookOpen size={22}/></span>클래스룸<span className="brand-period">.</span></a><div className="workspace"><span className="workspace-icon">C</span><div><strong>나의 배움 공간</strong><small>한 걸음 더 성장하는 오늘</small></div><span className="workspace-dot"/></div><p className="nav-label">LEARNING SPACE</p><nav><button className={view==='classes'?'active':''} onClick={()=>navigate('classes')}><LayoutGrid size={19}/>{creator?'내 강의 목록':'강의 둘러보기'}<ChevronRight size={15}/></button>{!creator&&<button className={view==='my'?'active':''} onClick={()=>navigate('my')}><GraduationCap size={20}/>내 수강 목록</button>}{creator&&<button onClick={()=>{setError('');setModal('create');}}><Plus size={19}/>새 강의 만들기</button>}</nav><div className="sidebar-bottom"><div className="sidebar-note"><span>작은 시작, 새로운 가능성</span><p>오늘의 배움이<br/>내일의 나를 만듭니다.</p><BookOpen size={29}/></div><div className="profile"><span className="avatar">{user?.userId?.slice(0,1).toUpperCase()||'G'}</span><div><strong>{user?.userId||'게스트'}</strong><small>{guest?'둘러보는 중':creator?'크리에이터':'클래스메이트'}</small></div>{!guest&&<button className="icon-button" aria-label="로그아웃" disabled={busy} onClick={logout}><LogOut size={18}/></button>}</div></div></aside>
 <div className="main-shell"><header className="topbar"><div><span className="topbar-label">나의 배움 공간</span><ChevronRight size={14}/><strong>{creator?'내 강의 목록':view==='my'?'내 수강 목록':'강의 둘러보기'}</strong></div><div className="top-actions"><span className="connection"><i/>{guest?'강의 둘러보는 중':'학습 공간 연결됨'}</span>{guest&&<button className="plain-button" onClick={()=>{setError('');setModal('login');}}>로그인 <ArrowUpRight size={16}/></button>}</div></header>
 <main>
 {error&&!modal&&<div className="error" role="alert">{error}<button onClick={refresh}>다시 시도</button></div>}
 <section id="catalog" className="catalog"><div className="catalog-heading"><h2>{creator?'내 강의 목록':view==='my'?'내 수강 목록':'클래스 둘러보기'} <span>{data.totalElements}</span></h2><button className="plain-button muted" onClick={refresh} disabled={loading}><RefreshCw size={14}/>새로고침</button></div><div className="toolbar"><div className="tabs">{(view==='my'?[['','신청 내역']]:[['OPEN','모집 중'],['DRAFT','모집 예정'],['CLOSED','모집 마감']]).map(([v,label])=><button key={v} className={state===v?'selected':''} onClick={()=>{setState(v);setPage(0);}}>{label}</button>)}</div><label className="search"><Search size={17}/><input aria-label="현재 페이지 강의 검색" placeholder="현재 페이지에서 강의 검색" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="검색 지우기" onClick={()=>setQuery('')}><X size={15}/></button>}</label></div><div className="results-caption"><span>{query?`검색 결과 ${shown.length}개`:creator?'개설한 강의를 모집 상태별로 확인하세요':'나에게 맞는 배움을 찾아보세요'}</span><span><SlidersHorizontal size={13}/>등록 순</span></div>
 {loading?<div className="empty" role="status">강의를 불러오고 있어요…</div>:shown.length===0?<div className="empty"><BookOpen size={32}/><h3>{query?'검색 결과가 없습니다':view==='my'?'아직 신청한 강의가 없어요':creator?'이 상태의 내 강의가 없습니다':'해당하는 강의가 없습니다'}</h3><p>{query?'다른 검색어로 찾아보세요.':'새로운 배움의 첫걸음을 시작해 보세요.'}</p><button className="primary" onClick={()=>{if(creator){setError('');setModal('create');}else navigate('classes');}}>{creator?'새 강의 만들기':'모집 중인 강의 보기'}</button></div>:<div className="course-grid">{shown.map((c,i)=>view==='my'?<article className="enrollment-card" key={c.enrollSeq}><span className={`badge ${c.enrollState}`}>{labels[c.enrollState]}</span><h3>{c.classTitle}</h3><p><CalendarDays size={15}/>{date(c.classStartDate)} ~ {date(c.classEndDate)}</p><button className="secondary" disabled={busy||c.enrollState==='CANCELLED'} onClick={()=>{setDetail(c);setModal('cancel');}}>수강 신청 취소</button></article>:<article className="course-card" key={c.classSeq}><button className="course-open" onClick={()=>openDetail(c)} disabled={busy}><Artwork kind={c.art} index={i}/><div className="course-body"><div className="course-meta"><span className={`badge ${c.classState}`}>{labels[c.classState]}</span><span>클래스 {String(c.classSeq).padStart(2,'0')}</span></div><h3>{c.classTitle}</h3><div className="course-capacity"><Users size={14}/>정원 {c.classMaxCap}명<span>함께 배우는 클래스</span></div><div className="course-footer"><strong>{money(c.classPrice)}</strong><span>자세히 보기 <ArrowUpRight size={15}/></span></div></div></button></article>)}</div>}
 {data.totalPages>1&&<div className="pagination"><button aria-label="이전 페이지" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>{page+1} / {data.totalPages}</span><button aria-label="다음 페이지" disabled={page+1>=data.totalPages} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div>}</section><footer className="footer"><span>classroom. <span>배움이 일상이 되는 공간</span></span><small>© {new Date().getFullYear()} Classroom</small></footer></main></div>
 {notice&&<div className="toast" role="status"><Check size={19}/>{notice}<button aria-label="알림 닫기" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {modal&&<Modal title={({login:'다시 만나 반가워요',signup:'배움의 여정을 시작하세요',detail:'클래스 살펴보기',create:'새 강의 만들기',edit:'강의 수정',cancel:'수강 신청 취소',delete:'강의 삭제'})[modal]} onClose={()=>{if(!busy){setModal(null);setError('');}}}>{error&&<div className="error" role="alert">{error}</div>}
 {(modal==='login'||modal==='signup')&&<form onSubmit={authenticate} className="form"><p className="muted">{modal==='login'?'로그인하고 나만의 배움을 이어가세요.':'클래스메이트 또는 크리에이터로 함께하세요.'}</p><label>아이디<input name="userId" required autoComplete="username" maxLength={100}/></label><label>비밀번호<input name="userPw" type="password" required autoComplete={modal==='login'?'current-password':'new-password'}/></label>{modal==='signup'&&<label>가입 유형<select name="userType"><option value="CLASSMATE">클래스메이트 · 수강생</option><option value="CREATOR">크리에이터 · 강사</option></select></label>}<button className="primary" disabled={busy}>{busy?'처리 중…':modal==='login'?'로그인':'회원가입'}</button><button type="button" className="plain-button" disabled={busy} onClick={()=>{setError('');setModal(modal==='login'?'signup':'login');}}>{modal==='login'?'처음이신가요? 회원가입':'이미 계정이 있나요? 로그인'}</button></form>}
 {modal==='detail'&&detail&&<div className="detail"><span className={`badge ${detail.classState}`}>{labels[detail.classState]}</span><h2>{detail.classTitle}</h2><p className="description">{detail.classContent}</p><div className="detail-info"><p><Users size={17}/>신청 인원 <strong>{detail.classCurrApps} / {detail.classMaxCap}명</strong></p><p><CalendarDays size={17}/>시작 <strong>{date(detail.classStartDate)}</strong></p><p><CalendarDays size={17}/>종료 <strong>{date(detail.classEndDate)}</strong></p></div><div className="detail-price">수강료<strong>{money(detail.classPrice)}</strong></div>{creator?<><p className="muted">수강생을 확인하고 강의를 관리하세요. 모집 예정 강의만 수정·삭제할 수 있습니다.</p><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>loadStudents()}>수강생 조회</button><button className="secondary" disabled={busy||detail.classState!=='DRAFT'} onClick={()=>setModal('edit')}>수정</button><button className="danger" disabled={busy||detail.classState!=='DRAFT'} onClick={()=>setModal('delete')}>삭제</button></div>{students&&<div className="student-list"><h3>수강생 {students.totalElements}명</h3>{students.content.map(s=><p key={s.enrollSeq}>{s.userId}</p>)}{!students.content.length&&<p>수강생이 없습니다.</p>}<div className="button-row"><button disabled={busy||studentPage===0} onClick={()=>loadStudents(studentPage-1)}>이전</button><button disabled={busy||studentPage+1>=students.totalPages} onClick={()=>loadStudents(studentPage+1)}>다음</button></div></div>}</>:<><button className="primary full" disabled={busy||detail.classState!=='OPEN'||detail.classCurrApps>=detail.classMaxCap||pending.includes(detail.classSeq)} onClick={enroll}>{busy?'접수 중…':pending.includes(detail.classSeq)?'신청 요청 접수됨':detail.classState!=='OPEN'?'현재 신청할 수 없는 강의입니다':detail.classCurrApps>=detail.classMaxCap?'정원이 마감되었습니다':guest?'로그인 후 수강 신청':'수강 신청'}</button><p className="fine-print">{guest?'수강 신청은 로그인 후 이용할 수 있습니다.':'신청은 순서대로 처리됩니다. 접수 후 내 수강 목록에서 결과를 확인하세요.'}</p></>}</div>}
 {(modal==='create'||modal==='edit')&&<form className="form" onSubmit={saveClass}><label>강의 제목<input name="classTitle" required defaultValue={modal==='edit'?detail.classTitle:''}/></label><label>강의 소개<textarea name="classContent" rows={4} required defaultValue={modal==='edit'?detail.classContent:''}/></label><div className="form-row"><label>수강료 (원)<input name="classPrice" type="number" min="0" step="1" required defaultValue={modal==='edit'?detail.classPrice:0}/></label><label>정원 (명)<input name="classMaxCap" type="number" min="1" step="1" required defaultValue={modal==='edit'?detail.classMaxCap:20}/></label></div><label>시작 일시<input name="classStartDate" type="datetime-local" required defaultValue={modal==='edit'?detail.classStartDate?.slice(0,16):''}/></label><label>종료 일시<input name="classEndDate" type="datetime-local" required defaultValue={modal==='edit'?detail.classEndDate?.slice(0,16):''}/></label><p className="fine-print">강의는 모집 예정 상태로 등록되며, 설정한 일시에 따라 상태가 변경됩니다.</p><button className="primary" disabled={busy}>{busy?'저장 중…':'강의 저장'}</button></form>}
 {(modal==='cancel'||modal==='delete')&&<div className="form"><p><strong>{detail.classTitle}</strong><br/>{modal==='cancel'?'이 강의의 수강 신청을 취소할까요?':'이 강의를 삭제할까요?'}</p><button className="danger" disabled={busy} onClick={()=>act(async()=>{if(modal==='cancel'){await request(`/enrollments/${detail.enrollSeq}`,{token,method:'DELETE'});}else await request(`/classes/${detail.classSeq}`,{token,method:'DELETE'});setModal(null);refresh();setNotice(modal==='cancel'?'수강 신청이 취소되었습니다.':'강의가 삭제되었습니다.');})}>{busy?'처리 중…':modal==='cancel'?'신청 취소하기':'삭제하기'}</button><button className="secondary" disabled={busy} onClick={()=>setModal(null)}>돌아가기</button></div>}
 </Modal>}
 </div>;
}
createRoot(document.getElementById('root')).render(<App/>);


